### PR TITLE
Make area presence radius configurable

### LINKED ISSUE #3: Create presence device for larger area - Not working
First, Great add-on for Hubitat. Everything works perfectly, except the "Create presence device for larger area" seletion.
When I select this in the Teslamate MQTT settings, it creates a child device with my car's name, followed by "nearby".
The problem isn't the creation of the device, but the fact it never changes state. When I leave my home (geo-fence), the presence state changes on the vehicle's presence will show "not present", but the "Nearby" device still shows "present". I drive away from the house > 20 miles, and still no change. When I get back to the house and my Teslamate system changes back to "Home", the vehicle device will change to "present" in hubitat, and the "Nearby" device still doesn't change at all.
I tried to turn off the feature and allow it to remove the device, then turn the feature back on so it can re-create it (it does), but it still doesn't change state when I leave the area.
I don't know how far away the "nearby" device needs to be before it changes to "not present", but it appears to be more than 40 miles.
I was hoping it would trigger outside of the "Home" geo-fence by a set distance (say 1/2 mile) so it could be used to turn the A/C setting when getting close to home to allow time to cool/heat before getting there. Since my geo-fence for "Home" is set for a 460 feet radius, I'm literally in the driveway when the geo-fence is triggered. I don't want to increase the radius of the geo-fence because I sometimes pass by the the house travelling from one town to the next, and the main road is only 800 feet from the house, and I don't want to trigger "coming home" routines when I'm only passing by. It would be great if the size of "Nearby" was selectable.

Please let me know if I'm doing something wrong, or expecting something that isn't going to happen. If you need more info, don't be afraid to ask, I'm more than happy to help.

### PR DESCRIPTION
**Pull request by MikeBishop**
Makes radius configurable, as in #3.

**NOTE:** This is almost completely untested at this point.

### CODE REVIEW

**Review by prussell69 — COMMENTED** [review]
Thank you BTW for your quick response! I've implemented your changes. I will test it out today and let you know how well it works. I have very high hopes it will.

**Comment by prussell69** [comment]
I tried [a8b9278] yestersday. I set the Radius for area presence device to 5 km. That seemed to work perfectly, however the vehicles presence never changed to "not present". I'm not sure if the problem stemed from my Teslamate system not updating the geofence, or if it was this driver. I added something on Teslamate (Grafana) so I can see what Teslamate is doing (hopefully).
I've updated the driver to e0703e3 (latest) to see how that does. I will let you know how it does.

**Comment by MikeBishop** [comment]
I found a bug around geofence handling that I think is fixed now, so hopefully the updated copy works.

**Comment by MikeBishop** [comment]
I can confirm that the latest version seems to be back to working well for my original use-case.  The question is, has it addressed yours with a smaller radius properly?

**Comment by prussell69** [comment]
Yes, it seems to be working fine. I'm experimenting with the distance setting. Trying to find the right distance. I'll let you know how it goes.

**Pull request merged**
